<!doctype html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
    <h1 class="text-center text-primary">Student Education Management System</h1>
     <div class="text-center">
		<a href="student-create-update" class="btn btn-primary">Add Students</a>
        <a href="teachers" class="btn btn-primary" >Add Teachers</a>
        <a href="subject" class="btn btn-primary" >Add Subjects</a>
        <a href="student-view" class="btn btn-primary" >Show Students</a>
        <a href="teacher-view" class="btn btn-primary" >Show Teachers</a>
        <a href="subject-view" class="btn btn-primary" >Show Subjects</a>
        <a href="parent-view" class="btn btn-primary" >Show Parents</a>
        <div>
    </div>
</body>
</html>